import type { ThemeConfig } from "antd";

/**
 * Get font family based on language/RTL direction
 */
function getFontFamily(isRTL?: boolean) {
	return isRTL
		? "'IranYekan', 'Tahoma', 'Arial', sans-serif"
		: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";
}

/**
 * تم تیره برند (Dark Theme) - همون چیزی که قبلاً داشتی
 */
const newBrandTheme = {
	token: {
		colorPrimary: "#1677FF",
		colorBgBase: "#1B1F3A",
		colorBgContainer: "#1E2440",
		colorBgElevated: "#1E2440",
		colorBgLayout: "#1B1F3A",
		colorBgSpotlight: "#1E2440",
		colorBorder: "transparent",
		colorBorderSecondary: "transparent",
		colorText: "#FFFFFF",
		colorTextBase: "#FFFFFF",
		colorTextSecondary: "#CACDD1",
		colorTextTertiary: "#9799A6",
		colorTextQuaternary: "#9799A6",
		colorSplit: "transparent",
		borderRadius: 10,
		borderRadiusLG: 8,
		borderRadiusSM: 4,
		wireframe: false,
		colorInfo: "#1677FF",
	},
	components: {
		Layout: {
			bodyBg: "#1B1F3A",
			headerBg: "#1E2440",
			siderBg: "#1E2440",
			footerBg: "#1B1F3A",
			headerColor: "#FFFFFF",
			triggerBg: "#1E2440",
		},
		Menu: {
			colorBgContainer: "#1E2440",
			itemBg: "#1E2440",
			subMenuItemBg: "#1E2440",
			colorText: "#9799A6",
			itemColor: "rgb(250,250,250)",
			itemHoverColor: "#FFFFFF",
			itemHoverBg: "#1677FF22",
			itemSelectedColor: "rgb(22,119,255)",
			itemSelectedBg: "#1F2E52",
			itemActiveBg: "#1F2E52",
			activeBarBorderWidth: 0,
			colorActiveBarBorderSize: 0,
			groupTitleColor: "#9799A6",
			darkItemBg: "#1E2440",
			darkSubMenuItemBg: "#1E2440",
			darkItemColor: "#9799A6",
			darkItemHoverColor: "#FFFFFF",
			darkItemSelectedColor: "#FFFFFF",
			darkItemSelectedBg: "#1F2E52",
			colorItemText: "#9799A6",
			colorItemTextSelected: "#FFFFFF",
			colorItemBgSelected: "#1F2E52",
			colorItemTextHover: "#FFFFFF",
			colorItemBgHover: "#1677FF22",
			popupBg: "#1E2440",
			colorBgBase: "#1E2440",
			itemBorderRadius: 12,
			subMenuItemBorderRadius: 8,
			borderRadius: 20,
			borderRadiusLG: 14,
		},
		Button: {
			borderRadiusSM: 16,
			borderRadiusLG: 8,
			borderRadius: 10,
		},
		Input: {
			colorBgContainer: "#1F2E52",
			colorBorder: "transparent",
			activeBorderColor: "transparent",
			hoverBorderColor: "transparent",
			colorText: "#FFFFFF",
			colorTextPlaceholder: "#9799A6",
			activeShadow: "none",
			errorActiveShadow: "none",
			warningActiveShadow: "none",
			paddingInline: 12,
			paddingBlock: 8,
		},
		InputNumber: {
			colorBgContainer: "#1F2E52",
			colorBorder: "transparent",
			activeBorderColor: "transparent",
			hoverBorderColor: "transparent",
			colorText: "#FFFFFF",
			colorTextPlaceholder: "#9799A6",
			activeShadow: "none",
			handleBg: "#1F2E52",
			handleHoverColor: "#1677FF",
			handleBorderColor: "transparent",
		},
		Select: {
			colorBgContainer: "#1F2E52",
			colorBorder: "transparent",
			colorPrimaryHover: "transparent",
			colorText: "#FFFFFF",
			colorTextPlaceholder: "#9799A6",
			optionSelectedBg: "#1677FF22",
			optionActiveBg: "#1F2E52",
			colorBgElevated: "#1E2440",
			selectorBg: "#1F2E52",
			activeOutlineColor: "transparent",
			activeBorderColor: "transparent",
			borderRadiusSM: 10,
			borderRadiusXS: 6,
		},
		AutoComplete: {
			colorBgContainer: "#1F2E52",
			colorBorder: "transparent",
			colorText: "#FFFFFF",
			colorTextPlaceholder: "#9799A6",
			colorBgElevated: "#1E2440",
		},
		Table: {
			colorBgContainer: "#1E2440",
			headerBg: "#1E2440",
			headerColor: "#FFFFFF",
			colorText: "#FFFFFF",
			rowHoverBg: "#1F2E52",
			borderColor: "#2E3D63",
			footerBg: "#1E2440",
			bodySortBg: "#1F2E52",
			headerSortHoverBg: "#2E3D63",
			headerSortActiveBg: "#2E3D63",
			fixedHeaderSortActiveBg: "#2E3D63",
			rowSelectedBg: "#1677FF22",
			rowSelectedHoverBg: "#1677FF33",
			headerSplitColor: "#2E3D63",
			filterDropdownBg: "#1E2440",
			expandIconBg: "#1F2E52",
			colorLink: "rgb(63,143,255)",
			colorPrimary: "rgb(63,143,255)",
			colorLinkActive: "rgb(73,144,244)",
			colorLinkHover: "rgb(54,138,255)",
			headerBorderRadius: 16,
			borderRadius: 16,
		},
		Card: {
			colorBgContainer: "#1E2440",
			colorBorderSecondary: "#2E3D63",
			colorText: "#FFFFFF",
			headerBg: "#1E2440",
			actionsBg: "#1E2440",
			extraColor: "#1677FF",
			borderRadiusLG: 20,
		},
		Modal: {
			contentBg: "#1E2440",
			headerBg: "#1E2440",
			footerBg: "#1E2440",
			colorText: "#FFFFFF",
			colorIcon: "#FFFFFF",
			colorIconHover: "#1677FF",
			colorBgMask: "#00000099",
			titleColor: "#FFFFFF",
			borderRadiusLG: 16,
			borderRadiusSM: 12,
		},
		Drawer: {
			colorBgElevated: "#1E2440",
			colorText: "#FFFFFF",
			colorIcon: "#FFFFFF",
			colorIconHover: "#1677FF",
			colorBgMask: "#00000099",
			footerPaddingBlock: 12,
			footerPaddingInline: 24,
			borderRadiusSM: 20,
		},
		Dropdown: {
			colorBgElevated: "#1E2440",
			colorText: "#FFFFFF",
			controlItemBgHover: "#1F2E52",
			controlItemBgActive: "#1677FF22",
			colorPrimary: "rgb(84,155,255)",
			borderRadiusLG: 20,
			borderRadiusSM: 10,
			borderRadiusXS: 6,
		},
		Tooltip: {
			colorBgSpotlight: "#1F2E52",
			colorTextLightSolid: "#FFFFFF",
		},
		Popover: {
			colorBgElevated: "#1E2440",
			colorText: "#FFFFFF",
			colorBorder: "#2E3D63",
		},
		Notification: {
			colorBgElevated: "#1E2440",
			colorText: "#FFFFFF",
			colorTextHeading: "#FFFFFF",
			colorIcon: "#FFFFFF",
			colorIconHover: "#1677FF",
			colorBorderSecondary: "#2E3D63",
			width: 384,
			borderRadiusLG: 16,
			borderRadiusSM: 12,
		},
		Message: {
			colorBgElevated: "#1E2440",
			colorText: "#FFFFFF",
			colorSuccess: "#52C41A",
			colorError: "#FF4D4F",
			colorWarning: "#FAAD14",
			colorInfo: "#1677FF",
			borderRadiusLG: 22,
		},
		FloatButton: {
			colorBgElevated: "#1E2440",
			colorText: "#FFFFFF",
			colorPrimary: "#1677FF",
			colorPrimaryHover: "#4096FF",
		},
		BackTop: {
			colorBgContainer: "#1F2E52",
			colorText: "#FFFFFF",
			colorPrimary: "#1677FF",
		},
		Alert: {
			colorInfoBg: "#1F2E52",
			colorInfoBorder: "#1677FF44",
			colorSuccessBg: "#0D2617",
			colorSuccessBorder: "#52C41A44",
			colorWarningBg: "#1F1800",
			colorWarningBorder: "#FAAD1444",
			colorErrorBg: "#2D0D0D",
			colorErrorBorder: "#FF4D4F44",
			borderRadiusLG: 20,
			lineType: "dashed",
		},
		Badge: {
			colorBgContainer: "#1E2440",
			colorError: "#FF4D4F",
			colorBorderBg: "#1E2440",
		},
		Tag: {
			colorBgContainer: "#1F2E52",
			colorBorder: "transparent",
			defaultBg: "rgba(22,119,255,0.12)",
			defaultColor: "rgb(57,139,255)",
			colorPrimary: "rgba(22,119,255,0.15)",
			colorIcon: "rgb(255,255,255)",
			colorText: "rgb(101,165,255)",
			colorPrimaryActive: "rgb(22,119,255)",
			colorPrimaryHover: "rgb(102,166,255)",
			colorTextLightSolid: "rgb(22,119,255)",
			colorFillSecondary: "rgba(22,119,255,0.1)",
			borderRadiusSM: 10,
			fontSizeSM: 14,
		},
		Tabs: {
			colorBgContainer: "rgba(22,119,255,0.11)",
			colorText: "rgb(255,255,255)",
			itemColor: "rgb(255,255,255)",
			itemHoverColor: "#FFFFFF",
			itemSelectedColor: "rgb(73,149,255)",
			inkBarColor: "rgb(34,125,252)",
			cardBg: "rgb(30,36,64)",
			colorBorderSecondary: "#2E3D63",
			itemActiveColor: "rgb(74,149,255)",
			borderRadius: 16,
			borderRadiusLG: 16,
			colorPrimaryBorder: "rgba(255,255,255,0)",
			colorBorder: "rgba(255,255,255,0)",
			colorIcon: "rgb(255,255,255)",
			lineWidth: 0,
			controlHeightLG: 48,
			cardGutter: 8,
		},
		Pagination: {
			colorBgContainer: "#1F2E52",
			colorBorder: "transparent",
			colorText: "#FFFFFF",
			itemActiveBg: "#1677FF",
			colorPrimary: "#1677FF",
			colorPrimaryHover: "#4096FF",
			itemInputBg: "#1F2E52",
			colorBgTextActive: "rgb(255,255,255)",
			itemActiveColor: "rgb(255,255,255)",
			borderRadius: 38,
			borderRadiusLG: 20,
			borderRadiusSM: 22,
		},
		Form: {
			labelColor: "#FFFFFF",
			labelRequiredMarkColor: "#FF4D4F",
			colorText: "#FFFFFF",
			colorError: "#FF4D4F",
			colorWarning: "#FAAD14",
			itemMarginBottom: 20,
		},
		Divider: {
			colorSplit: "#2E3D63",
			colorText: "#9799A6",
			orientationMargin: 0.05,
			textPaddingInline: 16,
			verticalMarginInline: 8,
		},
		Breadcrumb: {
			colorText: "#FFFFFF",
			colorTextDescription: "#9799A6",
			linkColor: "#1677FF",
			linkHoverColor: "#4096FF",
			separatorColor: "#9799A6",
			lastItemColor: "#FFFFFF",
			itemColor: "#9799A6",
		},
		Steps: {
			colorText: "#FFFFFF",
			colorTextDescription: "#9799A6",
			colorPrimary: "#1677FF",
			finishIconBorderColor: "#1677FF",
			finishTitleColor: "#FFFFFF",
			finishDescriptionColor: "#9799A6",
			processTitleColor: "#FFFFFF",
			processDescriptionColor: "#9799A6",
			waitTitleColor: "#9799A6",
			waitDescriptionColor: "#9799A6",
			waitIconBorderColor: "#9799A6",
			errorTitleColor: "#FF4D4F",
			errorDescriptionColor: "#FF4D4F",
		},
		Spin: {
			colorPrimary: "rgb(22,170,255)",
			colorBgContainer: "#1E2440",
			dotSize: 30,
			dotSizeSM: 16,
			dotSizeLG: 35,
		},
		Skeleton: {
			colorFill: "#2E3D63",
			colorFillContent: "#1F2E52",
			gradientFromColor: "#2E3D63",
			gradientToColor: "#1F2E52",
		},
		Progress: {
			colorSuccess: "#52C41A",
			colorText: "#FFFFFF",
			remainingColor: "#2E3D63",
			defaultColor: "#1677FF",
			circleTextColor: "#FFFFFF",
		},
		Slider: {
			colorPrimary: "#1677FF",
			colorPrimaryBorder: "#1677FF",
			colorPrimaryBorderHover: "#4096FF",
			colorFillTertiary: "#2E3D63",
			colorFillSecondary: "#2E3D63",
			colorBgElevated: "#1E2440",
			trackBg: "#1677FF",
			trackHoverBg: "#4096FF",
			handleColor: "#1677FF",
			handleActiveColor: "#4096FF",
			dotBorderColor: "#2E3D63",
			dotActiveBorderColor: "#1677FF",
		},
		Switch: {
			colorPrimary: "#1677FF",
			colorPrimaryHover: "#4096FF",
			colorTextQuaternary: "#9799A6",
			colorBgContainer: "#9799A6",
		},
		Checkbox: {
			colorBgContainer: "#1F2E52",
			colorBorder: "#1677FF",
			colorPrimary: "#1677FF",
			colorPrimaryHover: "#4096FF",
			colorText: "#FFFFFF",
			borderRadiusSM: 21,
		},
		Radio: {
			colorBgContainer: "#1F2E52",
			colorBorder: "#1677FF",
			colorPrimary: "rgb(44,131,252)",
			colorPrimaryHover: "rgb(127,183,252)",
			colorText: "#FFFFFF",
			buttonBg: "#1F2E52",
			buttonCheckedBg: "rgba(49,135,255,0.18)",
			buttonColor: "#FFFFFF",
			colorPrimaryActive: "rgb(21,84,173)",
			buttonSolidCheckedActiveBg: "rgb(22,119,255)",
		},
		DatePicker: {
			colorBgContainer: "#1F2E52",
			colorBorder: "transparent",
			activeBorderColor: "transparent",
			hoverBorderColor: "transparent",
			colorText: "#FFFFFF",
			colorTextPlaceholder: "#9799A6",
			colorBgElevated: "#1E2440",
			cellActiveWithRangeBg: "#1677FF22",
			cellHoverBg: "#1677FF33",
			activeShadow: "none",
		},
		TimePicker: {
			colorBgContainer: "#1F2E52",
			colorBorder: "transparent",
			activeBorderColor: "transparent",
			hoverBorderColor: "transparent",
			colorText: "#FFFFFF",
			colorTextPlaceholder: "#9799A6",
			colorBgElevated: "#1E2440",
			activeShadow: "none",
		},
		Transfer: {
			colorBgContainer: "#1F2E52",
			colorBorder: "#2E3D63",
			colorText: "#FFFFFF",
			headerBg: "#1E2440",
			itemHoverBg: "#1677FF22",
			itemSelectedBg: "#1677FF22",
			borderRadiusLG: 16,
		},
		Upload: {
			colorBgContainer: "#1F2E52",
			colorBorder: "#2E3D63",
			colorText: "#FFFFFF",
			colorTextDescription: "#9799A6",
			colorPrimary: "#1677FF",
			colorFillAlter: "#1F2E52",
			actionsColor: "#9799A6",
		},
		Collapse: {
			colorBgContainer: "#1E2440",
			colorBorder: "#2E3D63",
			colorText: "#FFFFFF",
			colorTextHeading: "#FFFFFF",
			headerBg: "#1F2E52",
			contentBg: "#1E2440",
			colorFillAlter: "#1F2E52",
			borderRadiusLG: 16,
		},
		Tree: {
			colorBgContainer: "transparent",
			colorText: "#FFFFFF",
			colorTextSecondary: "#9799A6",
			directoryNodeSelectedBg: "#1F2E52",
			directoryNodeSelectedColor: "#FFFFFF",
			nodeSelectedBg: "#1F2E52",
			nodeHoverBg: "#1677FF22",
			colorPrimary: "#1677FF",
		},
		Typography: {
			colorText: "#FFFFFF",
			colorTextSecondary: "#9799A6",
			colorTextDisabled: "#9799A6",
			colorLink: "#1677FF",
			colorLinkHover: "#4096FF",
			colorLinkActive: "#0958D9",
			titleMarginBottom: "0.5em",
			titleMarginTop: "1.2em",
		},
		Statistic: {
			colorText: "#FFFFFF",
			colorTextDescription: "#9799A6",
			contentFontSize: 28,
			titleFontSize: 14,
		},
		Avatar: {
			colorTextPlaceholder: "rgba(22,119,255,0.33)",
		},
		Image: {
			borderRadiusXS: 10,
		},
		Result: {
			colorText: "#FFFFFF",
			colorTextDescription: "#9799A6",
			iconFontSize: 72,
			titleFontSize: 24,
			subtitleFontSize: 14,
		},
		Empty: {
			colorText: "#9799A6",
			colorTextDescription: "#9799A6",
		},
		Anchor: {
			colorSplit: "#112045",
			inkBall: "#1754E1",
			linkPaddingBlock: 4,
			linkPaddingInlineStart: 16,
		},
		Timeline: {
			colorText: "#FFFFFF",
			colorTextSecondary: "#9799A6",
			colorPrimary: "#1677FF",
			dotBg: "#1E2440",
			tailColor: "#2E3D63",
		},
		Rate: {
			starBg: "#162A59",
			starColor: "#E8A838",
			starFontSize: 20,
			starHoverScale: "scale(1.1)",
			starSize: 20,
		},
		Segmented: {
			itemActiveBg: "rgba(22,119,255,0.22)",
			itemColor: "rgb(155,155,155)",
			itemHoverBg: "rgb(22,119,255)",
			itemSelectedBg: "rgba(22,119,255,0.17)",
			itemSelectedColor: "rgb(91,158,252)",
			borderRadius: 20,
			borderRadiusLG: 16,
			borderRadiusSM: 20,
			borderRadiusXS: 11,
		},
		TreeSelect: {
			colorBgContainer: "#1F2E52",
			colorBorder: "transparent",
			colorText: "#FFFFFF",
			colorTextPlaceholder: "#9799A6",
			colorBgElevated: "#1E2440",
			nodeSelectedBg: "#1677FF22",
		},
		Mentions: {
			colorBgContainer: "#1F2E52",
			colorBorder: "transparent",
			colorText: "#FFFFFF",
			colorTextPlaceholder: "#9799A6",
			colorBgElevated: "#1E2440",
		},
		Cascader: {
			colorBgContainer: "#1F2E52",
			colorBorder: "transparent",
			colorText: "#FFFFFF",
			colorTextPlaceholder: "#9799A6",
			colorBgElevated: "#1E2440",
			optionSelectedBg: "#1677FF22",
			borderRadiusSM: 10,
		},
	},
} as ThemeConfig;

/**
 * تم روشن برند (Light Theme) - جدید
 */
const newBrandLightTheme = {
	token: {
		colorPrimary: "#1677FF",
		colorBgBase: "#F5F7FA",
		colorBgContainer: "#FFFFFF",
		colorBgElevated: "#FFFFFF",
		colorBgLayout: "#F5F7FA",
		colorBgSpotlight: "#FFFFFF",
		colorBorder: "transparent",
		colorBorderSecondary: "transparent",
		colorText: "#0D1117",
		colorTextBase: "#0D1117",
		colorTextSecondary: "#4A5168",
		colorTextTertiary: "#8C90A0",
		colorTextQuaternary: "#8C90A0",
		colorSplit: "transparent",
		borderRadius: 10,
		borderRadiusLG: 8,
		borderRadiusSM: 4,
		wireframe: false,
		colorInfo: "#1677FF",
	},
	components: {
		Input: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "transparent",
			activeBorderColor: "transparent",
			hoverBorderColor: "transparent",
			colorText: "#0D1117",
			colorTextPlaceholder: "#8C90A0",
			activeShadow: "none",
			errorActiveShadow: "none",
			warningActiveShadow: "none",
			paddingInline: 12,
			paddingBlock: 8,
		},
		InputNumber: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "transparent",
			activeBorderColor: "transparent",
			hoverBorderColor: "transparent",
			colorText: "#0D1117",
			colorTextPlaceholder: "#8C90A0",
			activeShadow: "none",
			handleBg: "#EEF1F8",
			handleHoverColor: "#1677FF",
			handleBorderColor: "transparent",
		},
		Select: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "transparent",
			colorPrimaryHover: "transparent",
			colorText: "#0D1117",
			colorTextPlaceholder: "#8C90A0",
			optionSelectedBg: "#1677FF18",
			optionActiveBg: "#EEF1F8",
			colorBgElevated: "#FFFFFF",
			selectorBg: "#EEF1F8",
			activeOutlineColor: "transparent",
			activeBorderColor: "transparent",
			borderRadiusSM: 10,
			borderRadiusXS: 6,
		},
		AutoComplete: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "transparent",
			colorText: "#0D1117",
			colorTextPlaceholder: "#8C90A0",
			colorBgElevated: "#FFFFFF",
		},
		DatePicker: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "transparent",
			activeBorderColor: "transparent",
			hoverBorderColor: "transparent",
			colorText: "#0D1117",
			colorTextPlaceholder: "#8C90A0",
			colorBgElevated: "#FFFFFF",
			cellActiveWithRangeBg: "#1677FF18",
			cellHoverBg: "#1677FF28",
			activeShadow: "none",
		},
		TimePicker: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "transparent",
			activeBorderColor: "transparent",
			hoverBorderColor: "transparent",
			colorText: "#0D1117",
			colorTextPlaceholder: "#8C90A0",
			colorBgElevated: "#FFFFFF",
			activeShadow: "none",
		},
		Cascader: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "transparent",
			colorText: "#0D1117",
			colorTextPlaceholder: "#8C90A0",
			colorBgElevated: "#FFFFFF",
			optionSelectedBg: "#1677FF18",
			borderRadiusSM: 10,
		},
		TreeSelect: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "transparent",
			colorText: "#0D1117",
			colorTextPlaceholder: "#8C90A0",
			colorBgElevated: "#FFFFFF",
			nodeSelectedBg: "#1677FF18",
		},
		Mentions: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "transparent",
			colorText: "#0D1117",
			colorTextPlaceholder: "#8C90A0",
			colorBgElevated: "#FFFFFF",
		},
		Layout: {
			bodyBg: "#F5F7FA",
			headerBg: "#FFFFFF",
			siderBg: "#FFFFFF",
			footerBg: "#F5F7FA",
			headerColor: "#0D1117",
			triggerBg: "#FFFFFF",
		},
		Menu: {
			colorBgContainer: "#FFFFFF",
			itemBg: "#FFFFFF",
			subMenuItemBg: "#FFFFFF",
			colorText: "#8C90A0",
			itemColor: "#4A5168",
			itemHoverColor: "#1677FF",
			itemHoverBg: "#1677FF12",
			itemSelectedColor: "#1677FF",
			itemSelectedBg: "#EEF1F8",
			itemActiveBg: "#EEF1F8",
			activeBarBorderWidth: 0,
			colorActiveBarBorderSize: 0,
			groupTitleColor: "#8C90A0",
			darkItemBg: "#FFFFFF",
			darkSubMenuItemBg: "#FFFFFF",
			darkItemColor: "#8C90A0",
			darkItemHoverColor: "#1677FF",
			darkItemSelectedColor: "#1677FF",
			darkItemSelectedBg: "#EEF1F8",
			colorItemText: "#4A5168",
			colorItemTextSelected: "#1677FF",
			colorItemBgSelected: "#EEF1F8",
			colorItemTextHover: "#1677FF",
			colorItemBgHover: "#1677FF12",
			popupBg: "#FFFFFF",
			colorBgBase: "#FFFFFF",
			itemBorderRadius: 12,
			subMenuItemBorderRadius: 8,
			borderRadius: 20,
			borderRadiusLG: 14,
		},
		Table: {
			colorBgContainer: "#FFFFFF",
			headerBg: "#F5F7FA",
			headerColor: "#0D1117",
			colorText: "#0D1117",
			rowHoverBg: "#EEF1F8",
			borderColor: "#E4E8F0",
			footerBg: "#F5F7FA",
			bodySortBg: "#EEF1F8",
			headerSortHoverBg: "#E4E8F0",
			headerSortActiveBg: "#E4E8F0",
			fixedHeaderSortActiveBg: "#E4E8F0",
			rowSelectedBg: "#1677FF12",
			rowSelectedHoverBg: "#1677FF20",
			headerSplitColor: "#E4E8F0",
			filterDropdownBg: "#FFFFFF",
			expandIconBg: "#EEF1F8",
			colorLink: "#1677FF",
			colorPrimary: "#1677FF",
			colorLinkActive: "#0958D9",
			colorLinkHover: "#4096FF",
			headerBorderRadius: 16,
			borderRadius: 16,
		},
		Card: {
			colorBgContainer: "#FFFFFF",
			colorBorderSecondary: "#E4E8F0",
			colorText: "#0D1117",
			headerBg: "#FFFFFF",
			actionsBg: "#FFFFFF",
			extraColor: "#1677FF",
			borderRadiusLG: 20,
		},
		Modal: {
			contentBg: "#FFFFFF",
			headerBg: "#FFFFFF",
			footerBg: "#FFFFFF",
			colorText: "#0D1117",
			colorIcon: "#4A5168",
			colorIconHover: "#1677FF",
			colorBgMask: "#00000055",
			titleColor: "#0D1117",
			borderRadiusLG: 16,
			borderRadiusSM: 12,
		},
		Drawer: {
			colorBgElevated: "#FFFFFF",
			colorText: "#0D1117",
			colorIcon: "#4A5168",
			colorIconHover: "#1677FF",
			colorBgMask: "#00000055",
			footerPaddingBlock: 12,
			footerPaddingInline: 24,
			borderRadiusSM: 20,
		},
		Dropdown: {
			colorBgElevated: "#FFFFFF",
			colorText: "#0D1117",
			controlItemBgHover: "#EEF1F8",
			controlItemBgActive: "#1677FF12",
			colorPrimary: "#1677FF",
			borderRadiusLG: 20,
			borderRadiusSM: 10,
			borderRadiusXS: 6,
		},
		Tooltip: {
			colorBgSpotlight: "#1F2E52",
			colorTextLightSolid: "#FFFFFF",
		},
		Popover: {
			colorBgElevated: "#FFFFFF",
			colorText: "#0D1117",
			colorBorder: "#E4E8F0",
		},
		Tabs: {
			colorBgContainer: "rgba(22,119,255,0.07)",
			colorText: "#4A5168",
			itemColor: "#4A5168",
			itemHoverColor: "#1677FF",
			itemSelectedColor: "#1677FF",
			inkBarColor: "#1677FF",
			cardBg: "#F5F7FA",
			colorBorderSecondary: "#E4E8F0",
			itemActiveColor: "#1677FF",
			borderRadius: 16,
			borderRadiusLG: 16,
			colorPrimaryBorder: "rgba(0,0,0,0)",
			colorBorder: "rgba(0,0,0,0)",
			colorIcon: "#4A5168",
			lineWidth: 0,
			controlHeightLG: 48,
			cardGutter: 8,
		},
		Breadcrumb: {
			colorText: "#0D1117",
			colorTextDescription: "#8C90A0",
			linkColor: "#1677FF",
			linkHoverColor: "#4096FF",
			separatorColor: "#8C90A0",
			lastItemColor: "#0D1117",
			itemColor: "#8C90A0",
		},
		Badge: {
			colorBgContainer: "#FFFFFF",
			colorError: "#FF4D4F",
			colorBorderBg: "#FFFFFF",
		},
		Tag: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "transparent",
			defaultBg: "rgba(22,119,255,0.08)",
			defaultColor: "#1677FF",
			colorPrimary: "rgba(22,119,255,0.10)",
			colorIcon: "#4A5168",
			colorText: "#1677FF",
			colorPrimaryActive: "#0958D9",
			colorPrimaryHover: "#4096FF",
			colorTextLightSolid: "#1677FF",
			colorFillSecondary: "rgba(22,119,255,0.07)",
			borderRadiusSM: 10,
			fontSizeSM: 14,
		},
		Alert: {
			colorInfoBg: "#E8F0FF",
			colorInfoBorder: "#1677FF44",
			colorSuccessBg: "#E8F8EE",
			colorSuccessBorder: "#52C41A44",
			colorWarningBg: "#FFFBE6",
			colorWarningBorder: "#FAAD1444",
			colorErrorBg: "#FFF1F0",
			colorErrorBorder: "#FF4D4F44",
			borderRadiusLG: 20,
			lineType: "dashed",
		},
		Form: {
			labelColor: "#0D1117",
			labelRequiredMarkColor: "#FF4D4F",
			colorText: "#0D1117",
			colorError: "#FF4D4F",
			colorWarning: "#FAAD14",
			itemMarginBottom: 20,
		},
		Checkbox: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "#1677FF",
			colorPrimary: "#1677FF",
			colorPrimaryHover: "#4096FF",
			colorText: "#0D1117",
			borderRadiusSM: 21,
		},
		Radio: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "#1677FF",
			colorPrimary: "#1677FF",
			colorPrimaryHover: "#4096FF",
			colorText: "#0D1117",
			buttonBg: "#EEF1F8",
			buttonCheckedBg: "rgba(22,119,255,0.12)",
			buttonColor: "#0D1117",
			colorPrimaryActive: "#0958D9",
			buttonSolidCheckedActiveBg: "#1677FF",
		},
		Switch: {
			colorPrimary: "#1677FF",
			colorPrimaryHover: "#4096FF",
			colorTextQuaternary: "#8C90A0",
			colorBgContainer: "#C0C4CF",
		},
		Slider: {
			colorPrimary: "#1677FF",
			colorPrimaryBorder: "#1677FF",
			colorPrimaryBorderHover: "#4096FF",
			colorFillTertiary: "#E4E8F0",
			colorFillSecondary: "#E4E8F0",
			colorBgElevated: "#FFFFFF",
			trackBg: "#1677FF",
			trackHoverBg: "#4096FF",
			handleColor: "#1677FF",
			handleActiveColor: "#4096FF",
			dotBorderColor: "#E4E8F0",
			dotActiveBorderColor: "#1677FF",
		},
		Upload: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "#E4E8F0",
			colorText: "#0D1117",
			colorTextDescription: "#8C90A0",
			colorPrimary: "#1677FF",
			colorFillAlter: "#EEF1F8",
			actionsColor: "#8C90A0",
		},
		Transfer: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "#E4E8F0",
			colorText: "#0D1117",
			headerBg: "#FFFFFF",
			itemHoverBg: "#1677FF12",
			itemSelectedBg: "#1677FF12",
			borderRadiusLG: 16,
		},
		Pagination: {
			colorBgContainer: "#EEF1F8",
			colorBorder: "transparent",
			colorText: "#0D1117",
			itemActiveBg: "#1677FF",
			colorPrimary: "#1677FF",
			colorPrimaryHover: "#4096FF",
			itemInputBg: "#EEF1F8",
			colorBgTextActive: "#FFFFFF",
			itemActiveColor: "#FFFFFF",
			borderRadius: 38,
			borderRadiusLG: 20,
			borderRadiusSM: 22,
		},
		Steps: {
			colorText: "#0D1117",
			colorTextDescription: "#8C90A0",
			colorPrimary: "#1677FF",
			finishIconBorderColor: "#1677FF",
			finishTitleColor: "#0D1117",
			finishDescriptionColor: "#8C90A0",
			processTitleColor: "#0D1117",
			processDescriptionColor: "#8C90A0",
			waitTitleColor: "#8C90A0",
			waitDescriptionColor: "#8C90A0",
			waitIconBorderColor: "#8C90A0",
			errorTitleColor: "#FF4D4F",
			errorDescriptionColor: "#FF4D4F",
		},
		Timeline: {
			colorText: "#0D1117",
			colorTextSecondary: "#8C90A0",
			colorPrimary: "#1677FF",
			dotBg: "#FFFFFF",
			tailColor: "#E4E8F0",
		},
		Collapse: {
			colorBgContainer: "#FFFFFF",
			colorBorder: "#E4E8F0",
			colorText: "#0D1117",
			colorTextHeading: "#0D1117",
			headerBg: "#EEF1F8",
			contentBg: "#FFFFFF",
			colorFillAlter: "#EEF1F8",
			borderRadiusLG: 16,
		},
		Tree: {
			colorBgContainer: "transparent",
			colorText: "#0D1117",
			colorTextSecondary: "#8C90A0",
			directoryNodeSelectedBg: "#EEF1F8",
			directoryNodeSelectedColor: "#1677FF",
			nodeSelectedBg: "#EEF1F8",
			nodeHoverBg: "#1677FF12",
			colorPrimary: "#1677FF",
		},
		Statistic: {
			colorText: "#0D1117",
			colorTextDescription: "#8C90A0",
			contentFontSize: 28,
			titleFontSize: 14,
		},
		Typography: {
			colorText: "#0D1117",
			colorTextSecondary: "#4A5168",
			colorTextDisabled: "#8C90A0",
			colorLink: "#1677FF",
			colorLinkHover: "#4096FF",
			colorLinkActive: "#0958D9",
			titleMarginBottom: "0.5em",
			titleMarginTop: "1.2em",
		},
		Divider: {
			colorSplit: "#E4E8F0",
			colorText: "#8C90A0",
			orientationMargin: 0.05,
			textPaddingInline: 16,
			verticalMarginInline: 8,
		},
		Progress: {
			colorSuccess: "#52C41A",
			colorText: "#0D1117",
			remainingColor: "#E4E8F0",
			defaultColor: "#1677FF",
			circleTextColor: "#0D1117",
		},
		Spin: {
			colorPrimary: "#1677FF",
			colorBgContainer: "#FFFFFF",
			dotSize: 30,
			dotSizeSM: 16,
			dotSizeLG: 35,
		},
		Skeleton: {
			colorFill: "#E4E8F0",
			colorFillContent: "#EEF1F8",
			gradientFromColor: "#E4E8F0",
			gradientToColor: "#EEF1F8",
		},
		Empty: {
			colorText: "#8C90A0",
			colorTextDescription: "#8C90A0",
		},
		Result: {
			colorText: "#0D1117",
			colorTextDescription: "#8C90A0",
			iconFontSize: 72,
			titleFontSize: 24,
			subtitleFontSize: 14,
		},
		Notification: {
			colorBgElevated: "#FFFFFF",
			colorText: "#0D1117",
			colorTextHeading: "#0D1117",
			colorIcon: "#4A5168",
			colorIconHover: "#1677FF",
			colorBorderSecondary: "#E4E8F0",
			width: 384,
			borderRadiusLG: 16,
			borderRadiusSM: 12,
		},
		Message: {
			colorBgElevated: "#FFFFFF",
			colorText: "#0D1117",
			colorSuccess: "#52C41A",
			colorError: "#FF4D4F",
			colorWarning: "#FAAD14",
			colorInfo: "#1677FF",
			borderRadiusLG: 22,
		},
		FloatButton: {
			colorBgElevated: "#FFFFFF",
			colorText: "#0D1117",
			colorPrimary: "#1677FF",
			colorPrimaryHover: "#4096FF",
		},
		BackTop: {
			colorBgContainer: "#EEF1F8",
			colorText: "#0D1117",
			colorPrimary: "#1677FF",
		},
		Avatar: {
			colorTextPlaceholder: "rgba(22,119,255,0.25)",
		},
		Image: {
			borderRadiusXS: 10,
		},
		Segmented: {
			itemActiveBg: "rgba(22,119,255,0.15)",
			itemColor: "#8C90A0",
			itemHoverBg: "rgba(22,119,255,0.08)",
			itemSelectedBg: "rgba(22,119,255,0.10)",
			itemSelectedColor: "#1677FF",
			borderRadius: 20,
			borderRadiusLG: 16,
			borderRadiusSM: 20,
			borderRadiusXS: 11,
		},
		Button: {
			borderRadiusSM: 16,
			borderRadiusLG: 8,
			borderRadius: 10,
		},
	},
	algorithm: [],
} as ThemeConfig;

/**
 * پیکربندی تم روشن سفارشي Ant Design
 */
export const customAntdLightTheme: ThemeConfig = newBrandLightTheme;

/**
 * پیکربندی تم تیره سفارشي Ant Design
 */
export const customAntdDarkTheme: ThemeConfig = newBrandTheme;

/**
 * Get theme configuration with dynamic font family based on RTL
 */
export function getCustomAntdTheme(isDark: boolean, isRTL: boolean): ThemeConfig {
	const baseTheme = isDark ? customAntdDarkTheme : customAntdLightTheme;

	return {
		...baseTheme,
		token: {
			...baseTheme.token,
			fontFamily: getFontFamily(isRTL),
		},
	};
}
